### ISSUE TITLE
询问一个问题。

### ISSUE THREAD

**Issue by shengruqing** [ialex32x/unityfs#12]
在Build Packages的时候，打包的资源是不是必须有一个要要设置为FileList类型？如果不设置fileListManifest就会报空，无法打包。
希望大佬可以出一个详细的打包教程。

**Comment by ialex32x** [comment]
失误了, 需要判一下空. 
目前项目里在用, 有些地方设计得不是非常理想, 可能以后再重构设计一版再考虑详细做一些文档工作了 :)

**Comment by ialex32x** [comment]
已修改提交
