### ISSUE TITLE
有个小bug

### ISSUE THREAD

**Issue by shengruqing** [ialex32x/unityfs#14]
AssetHandle脚本的CreateInstance方法中
`        public static AssetHandle CreateInstance(UAsset asset, float ttl)
        {
            var gameObject = Object.Instantiate(asset.GetObject()) as GameObject;
            return UnityFS.Utils.AssetHandle.Attach(gameObject, asset, 5.0f);
        }`
这段代码中的5.0f之后删除应该是测试时留的没修改掉吧？应该使用上面定义的参数ttl吧。如果不修改为ttl。prefab每次创建5秒之后就会被强制删除。
还有一个问题，能否获取所有资源的路径（有些物品的路径可能不在同一个资源目录下面，动态获取资源的时候就无法知道路径了）在登陆的时候把所有路径存起来，需要获取资源的时候直接通过资源名就可以了，路径通过资源名在字典中取。

**Comment by shengruqing** [comment]
脚本中有个这个方法，但是好像并没实现具体功能SearchAsset

**Comment by ialex32x** [comment]
嗯, 因为原本有这个打算, 后来发现没有实际项目需求, 所以一直没有去做. 前面提到的获取路径是指所有资源的路径? 还是特定匹配规则下的一些路径?

**Comment by ialex32x** [comment]
参数确实错了, 项目里一直没实际用上这个辅助类一直没发现, 多谢指出啦 :)

**Comment by shengruqing** [comment]
所有打包资源的完整路径，在资源加载完成之后就可以获取到完整的资源路径 例如：Assets/Examples/Config/test.txt
Assets/Examples/Prefabs/Cube 1.prefab

**Comment by ialex32x** [comment]
能否给出一小段伪代码
```cs
// 是指这种吗?
var paths = ResourceManager.GetAllAssetPaths();
...
```

**Comment by shengruqing** [comment]
对的。就是这种。

> 
// 是指这种吗?
string [] paths = ResourceManager.GetAllAssetPaths();
...
>

**Comment by ialex32x** [comment]
这个有点问题, 主要是实际模式和编辑器模式需要统一, 现在的做法是编辑器模式下运行是无视打包规则的 (没有清单, 因为可以不打包直接运行), 也就是并不知道最终会是哪些资源会进入打包, 所以要么两种运行方式的返回值不一致, 要么编辑器模式也需要读取打包规则. 
最初是希望编辑器模式下可以对打包配置无感的.

**Comment by shengruqing** [comment]
其实填完整路径也是可以的，但是总感觉很麻烦，比如某个资源修改了存储路径，就要把配置或者代码中的路径也同时修改。如果能直接通过资源名称获取到资源，会非常方便，也会减少很多工作量。

**Comment by ialex32x** [comment]
这个倒是可以考虑还是实现一下
```cs 
LoadAsset("**/xxx.prefab"); 
或者
SearchAsset("**/xxx.prefab");
```
类似这样的方式去自动搜索.

**Comment by ialex32x** [comment]
另外会再加一个只给出 object.name 就得到 Asset 的方式. 不过资源名重复的话就没法正确区分了.

**Comment by shengruqing** [comment]
其实，在选择需要热更资源的时候，就已经知道相对路径了（Bundle Builder面板中Add资源的时候）。在使用资源的时候去目录中搜索相应资源，搜索到资源资直接返回就可以了，源路径可以存在一个字典中，下次使用的时候如果字典中存在路径，就不用重复搜索了，减少搜索次数。一般资源管理规范，不会出现资源名称重复的（资源名加上后缀例如：.prefab、.txt、.unity）。
