### ISSUE TITLE
请问如何读取TexturePacker图集中指定图片？

### ISSUE THREAD

**Issue by 8086694** [ialex32x/unityfs#15]
加载资源时如何读取TexturePacker图集内的图片。
_        var sprite = UnityFS.ResourceManager.LoadAsset<Sprite>(atlasPath);
        sprite.completed += self =>
        {
            if (func != null) func.Call(sprite.GetObject<Sprite>());
        };
_
使用上面的代码读取只能读取到图集中的第一张图片，无法读取图集中指定的图片。

**Comment by ialex32x** [comment]
是指 Unity 自带的 Sprite Packer 图集吗? 如果是的话就像读图片一样得到 Sprite

**Comment by 8086694** [comment]
不是unity自带的图集。使用TexturePacker打包的图集。

**Comment by 8086694** [comment]
[test.zip](https://github.com/ialex32x/unityfs/files/4656397/test.zip)
测试demo，Sample.cs脚本中的OnAllStartupsLoaded方法里面有提供相应测试代码和图集

**Comment by ialex32x** [comment]
支持了一下, 已提交. 稍微有点trick, 需要在传入的 asset path 上附带要得到的 sprite 名.

```cs
            var testFile = ResourceManager.LoadAsset<Sprite>("Assets/Examples/Image/test.png@Dg7");
            testFile.completed += self =>
            {
                AssetHandle.Attach(testSprite.gameObject, self);
                testSprite.sprite = self.GetObject<Sprite>();
            };
```

目前的话单图多Sprite的情况注意打包的时候打图集文件本身. 不要单独打里面的Sprite. 后续应该会再完善这块.

**Comment by 8086694** [comment]
ok,我试一试。

**Comment by ialex32x** [comment]
'@' 容易出现在正常文件名中, 改成 Manifest.SubAssetSeperator 常量定义了, 默认 '>'
