### ISSUE TITLE
有没有办法登录游戏之后所有的加载均使用同步的方式？

### ISSUE THREAD

**Issue by 8086694** [ialex32x/unityfs#16]
有没有办法登录游戏之后所有的资源加载均使用同步的方式？现在使用异步加载资源，很多需要同步加载的资源会有问题，例如：释放一个技能，点击释放技能之后，零点几秒之后才会显示出来特效，但是技能的动作已经播放完毕。全部使用异步的方式加载，卡顿非常明显。而且现在如果需要在异步的加载方法里面再嵌套一个异步加载资源，也是不允许的，在异步中使用同步的时候，也会出现加载不到资源的情况。UnityFS.ResourceManager.Instantiate(“asset/ss”).target;如果能在登录游戏之后，资源采用异步的方式加载，应该会好很多，也会减少很多代码吧。

**Comment by ialex32x** [comment]
一般这种情况比较合理的解决方法是预加载之后自己管理实例化, 即使是同步加载, 也会因为加载实例化的卡顿而选择预加载, 基本是规避不掉的 (配置文件等除外, 但大部分配置的载入其实也算预加载, 基本游戏启动就读好了).
加同步接口的主要问题是不可靠不一致, 因为对应的包以及依赖包都有可能需要下载, 所以异步处理适应性是相对最好的.
不过可以考虑加一组接口, 如果资源就绪, 就可以同步取到资源, 否则退化为异步加载.

**Comment by ialex32x** [comment]
增加了 TryLoadAssetSync 接口
