### ISSUE TITLE
编辑器模式下资源加载材质问题。

### ISSUE THREAD

**Issue by shengruqing** [ialex32x/unityfs#19]
编辑器模式下（android或者ios平台），非开发者模式，材质，shader，灯光会出现失效，需要代码重新设置。

**Comment by shengruqing** [comment]
目前我在加载的时候重新设置了prefab的hader，希望能处理一下。
`#if UNITY_EDITOR && (UNITY_ANDROID || UNITY_IOS)
            Renderer[] renderers = go.GetComponentsInChildren<Renderer>();
            foreach (Renderer r in renderers)
            {
                string shaderName = r.sharedMaterial.shader.name;
                r.sharedMaterial.shader = Shader.Find(shaderName);
            }
            Projector[] projecters = go.GetComponentsInChildren<Projector>();
            foreach (Projector p in projecters)
            {
                string shaderName = p.material.shader.name;
                p.material.shader = Shader.Find(shaderName);
            }
#endif`

**Comment by shengruqing** [comment]
非开发模式下，图集加载好像也有问题，加载不到。开发模式下没问题。

**Comment by ialex32x** [comment]
材质的问题是因为打包产生的是对应平台的shader, 虽然编辑器target platform 是目标平台, 但实际运行时gpu还是pc, 所以, 如果要在编辑器中使用assetbundle模式加载资源, 一般只能用windows作为目标平台, 并打包windows目标平台的包, 进行载入. (这是Assetbundle本身的限制)

**Comment by ialex32x** [comment]
图集的问题我查一下

**Comment by ialex32x** [comment]
```cs
var testFile = ResourceManager.LoadAsset<Sprite>("Assets/Examples/Image/test.png");
            testFile.completed += self =>
            {
                UnityFS.Utils.AssetHandle.Attach(testSprite.gameObject, self);
                testSprite.sprite = self.GetObject<Sprite>("Dg2");
            };
```

图集加载的问题试了一下可以加载, 确认一下图集资源是不是进了打包? 另外因为没有额外的引用关系, 所以如果没有 ```cs UnityFS.Utils.AssetHandle.Attach(testSprite.gameObject, self);``` 这句的话图集资源是会被回收的. 建议自己实现一个辅助类完成图集的加载和Sprite的赋值以及图集资源的引用保持 (这方面不是非常通用, 因此没有提供现成的辅助封装)

后续会针对没进打包的问题改进一下, 如果资源分析列表中存在的资源没进打包, 给出提示.
